export enum Role {
  PM = "PM",
  ENG = "ENG",
  RES = "RES"
}

export enum EventType {
  MORE_IMPORTANT = "MORE_IMPORTANT",
  LESS_IMPORTANT = "LESS_IMPORTANT",
  COMPLETED = "COMPLETED",
  SCHEDULED = "SCHEDULED",
  IGNORED = "IGNORED",
  REMIND_7D = "REMIND_7D",
  OPEN_SOURCE = "OPEN_SOURCE",
  MARK_RELEVANT = "MARK_RELEVANT",
  MARK_NOT_RELEVANT = "MARK_NOT_RELEVANT",
  ASK_SOMEONE_SENT = "ASK_SOMEONE_SENT",
  DEFERRED_BUT_IMPORTANT = "DEFERRED_BUT_IMPORTANT",
  CARD_REVISITED = "CARD_REVISITED",
  CARD_REFERENCED = "CARD_REFERENCED"
}

export enum ItemStatus {
  NEW = "NEW",
  TRIAGED = "TRIAGED",
  SCHEDULED = "SCHEDULED",
  IGNORED = "IGNORED",
  COMPLETED = "COMPLETED",
  CARD_CREATED = "CARD_CREATED"
}
